packages:
  - "chess-api"
  - "chess-api/admin-frontend"
  - "chess-client"
  - "website"
allowBuilds:
  '@parcel/watcher': set this to true or false
  better-sqlite3: set this to true or false
  electron: false
  esbuild: true
  stockfish: false
