#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

PORT="${PORT:-25566}"
TUNNEL="${TUNNEL:-}"
CLIENT_ENV_FILE="../chess-client/.env"

usage() {
  cat <<EOF
Usage: $0 [--native | -n] [--tunnel <tool>] [--port <num>] [--no-client-env]

Start the chess-api server.

Options:
  --native, -n        Run natively (npm run dev) instead of Docker
  --tunnel <tool>     Expose via tunnel (ngrok | cloudflared)
  --port <num>        Host port (default: 25566, maps to container port 3000)
  --no-client-env     Skip updating chess-client/.env with tunnel URL
  --help, -h          Show this help

Examples:
  $0                          # Docker on port 25566
  $0 --native                 # npm run dev on port 3000
  $0 --tunnel cloudflared     # Docker + cloudflare tunnel
  $0 --native --tunnel ngrok  # Native + ngrok tunnel
EOF
  exit 0
}

UPDATE_CLIENT_ENV=true
while [[ $# -gt 0 ]]; do
  case "$1" in
    --native|-n) MODE="native"; shift ;;
    --tunnel) TUNNEL="${2:-}"; shift 2 ;;
    --port) PORT="${2:-}"; shift 2 ;;
    --no-client-env) UPDATE_CLIENT_ENV=false; shift ;;
    --help|-h) usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

export PORT

write_client_env() {
  local url="$1"
  local env_file="$CLIENT_ENV_FILE"
  local prev_file="${env_file}.bak"

  if [[ -f "$env_file" ]]; then
    cp "$env_file" "$prev_file"
    echo "Saved previous client env to $prev_file"
  fi

  echo "# Auto-generated by chess-api/start.sh --tunnel" > "$env_file"
  echo "CHESS_SERVER_URL=$url" >> "$env_file"
  echo "Updated $env_file with CHESS_SERVER_URL=$url"
}

start_tunnel() {
  local local_port="$1"
  local tunnel_url=""

  case "$TUNNEL" in
    ngrok)
      echo "Starting ngrok tunnel on port $local_port ..."
      ngrok http "$local_port" --log=stdout 2>/dev/null &
      sleep 3
      tunnel_url=$(curl -s http://127.0.0.1:4040/api/tunnels 2>/dev/null | python3 -c "import sys,json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])" 2>/dev/null || true)
      ;;
    cloudflared)
      echo "Starting cloudflared tunnel on port $local_port ..."
      local tmpfile
      tmpfile=$(mktemp)
      cloudflared tunnel --url "http://localhost:$local_port" 2>&1 | tee "$tmpfile" &
      sleep 4
      tunnel_url=$(grep -oP 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' "$tmpfile" 2>/dev/null | head -1 || true)
      rm -f "$tmpfile"
      ;;
    *)
      if [[ -n "$TUNNEL" ]]; then
        echo "Unknown tunnel tool '$TUNNEL'. Use 'ngrok' or 'cloudflared'." >&2
        exit 1
      fi
      return
      ;;
  esac

  if [[ -n "$tunnel_url" ]]; then
    echo "Tunnel URL: $tunnel_url"
    if $UPDATE_CLIENT_ENV; then
      write_client_env "$tunnel_url"
    fi
    echo "Start the client normally — it will use the tunnel URL."
    echo "To restore localhost URL, run: cp $CLIENT_ENV_FILE.bak $CLIENT_ENV_FILE 2>/dev/null; rm -f $CLIENT_ENV_FILE"
  else
    echo "Warning: Could not detect tunnel URL. Client env not updated." >&2
  fi
}

cleanup() {
  echo
  echo "Shutting down ..."
  docker compose down 2>/dev/null || true
}

stop_docker() {
  cleanup
  exit 0
}

if [[ "${MODE:-docker}" == "native" ]]; then
  echo "Starting chess-api natively on port $PORT ..."
  if [[ ! -d dist ]]; then
    echo "Building first ..."
    npm run build
  fi
  start_tunnel "$PORT"
  exec npm start
else
  echo "Starting chess-api in Docker on port $PORT -> 3000 ..."
  docker compose up --build -d
  start_tunnel "$PORT"
  echo "Server running at http://localhost:$PORT"
  echo
  echo "Press q to stop and remove the container"
  while true; do
    read -rsn 1 key
    if [[ "$key" == "q" ]]; then
      stop_docker
    fi
  done
fi
